[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[build_meta]
author= "Vincent Weinhold"
url = "https://github.com/Simulation-Software-Engineering/diffusion2d.git"

[project]
name = "weinhovt-diffusion2d"
description = "Small solver for 2d diffusion."
readme = "README.md"
version = "0.0.1"
requires-python = ">=3.6"
license = {text = "CC-BY-4.0 License"}
dependencies = ["matplotlib", "numpy"]
